car:
  size: small
  color: red
  arrayProps: 1,2,3,4,5
  listNames:
    - name: BMW
    - name: 福特
  listMaps:
    - name: price
      value: 1000
    - name: unit
      vaule: 元
  mapProps:
    key1: value1
    key2: value2